### ISSUE TITLE
Alvearie website - potential updates to assess

### ISSUE THREAD

**Issue by thisisadamo** [Alvearie/alvearie.github.io#1]
What is:

"With IBM Watson Health's Project Alvearie enterprises and developers can harness interoperable, cloud-agnostic, enterprise-grade components, purpose-built for verticals across healthcare and developed by both IBM and ecosystem partners. With those components, developers can leverage and build solutions upon interoperable health-specific components & tools, developed by IBM, ecosystem partners, and the wider developer community. Developers can solve for data access, ingestion, integration, analytics, ML/DL, batch and real-time and more."

Objectives:

Transform healthcare technology through an open ecosystem with composable services aligned with open standards delivered via cloud agnostic open technology.  
Build an extensible, modular, scalable set of components that can be pipelined aligned with common industry-standard data models.   
Be the leading reference implementations that highlight how to combine various technologies into meaningful patterns for healthcare.
Enable data to be the asset, vs. a drag.  (need something better here)

**Comment by mannyveiga** [comment]
@thisisadamo I made some changes to the Alvearie Developer POV since that version you saw. What do you think of this for the "What is" paragraph?

Project Alvearie is an open-source project bringing together contributors from across the health and life sciences ecosystem for collaboration around common and pervasive challenges to health data ingestion and flow. Together, we are working to build a set of an extensible, modular and scalable multi-cloud data and analytics components that can help organizations improve care delivery and operate more efficiently in a highly regulated environment

Developers can access a collection of assets capable of ingesting and orchestrating FHIR, HL7, DICOM, and X12, and leveraging Apache Spark and Flink for distributed big data processing and analytics. Developers can also leverage or contribute to reference implementations that highlight how to combine various technologies into meaningful patterns for healthcare.

**Comment by thisisadamo** [comment]
> @thisisadamo I made some changes to the Alvearie Developer POV since that version you saw. What do you think of this for the "What is" paragraph?
> 
> Project Alvearie is an open-source project bringing together contributors from across the health and life sciences ecosystem for collaboration around common and pervasive challenges IN CREATING APPLICATIONS, ANALYTICS, OR SOFTWARE THAT USES HEALTH DATA.  Together, OUR MISSION IS to build a set of an extensible, modular and scalable multi-cloud data and analytics components that can help organizations improve care delivery and operate more efficiently in a highly regulated environment.
> 
> Developers can access a collection of assets capable of ingesting and orchestrating FHIR, HL7, DICOM, and X12, and leveraging Apache Spark and Flink for distributed big data processing and analytics. Developers can also leverage or contribute to reference implementations that highlight how to combine various technologies into meaningful patterns for healthcare.

CAPS above.. :-)

**Comment by eggebraa** [comment]
The new wording is now available on the Alvearie website, in addition to some other design changes.
